version: "3.9"
services:
  php:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    container_name: "srv-php80"
    image: server-apache-php80
    volumes:
      - ./:/var/www/html
      - ./docker/personal.ini:/usr/local/etc/php/conf.d/personal.ini
      - ./docker/apache/lvh.me.crt:/etc/ssl/certs/lvh.me.crt
      - ./docker/apache/lvh.me.key:/etc/ssl/private/lvh.me.key
      - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/imagick/policy.xml:/etc/ImageMagick-6/policy.xml
    ports:
      - '${ERYKIA_PORT:-80}:80'
      - '${ERYKIA_SSL_PORT:-443}:443'
    restart: always
    networks:
      - erykianet

  mysql:
    image: mariadb:10.8.2
    container_name: "srv-mariadb"
    volumes:
      - ./_db-docker-dev_/data:/var/lib/mysql
      - ./_db-docker-dev_/logs:/var/log/mysql
      - ./_db-docker-dev_/conf:/etc/mysql
      - ./docker/init.sql:/data/application/init.sql
    ports:
      - '${ERIKIA_DB_PORT:-3306}:3306'
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - erykianet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "srv-phpmyadmin"
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=300M
    links:
      - mysql
    restart: always
    networks:
      - erykianet

networks:
  erykianet:
    driver: bridge
