<?php

namespace Source\Model;

use Source\Core\Model;

class User extends Model
{
    public function __construct()
    {
        parent::__construct(
            'users',
            [
                'name',
                'email',
                'password',
                'level'
            ]
        );
    }

    public function emailFilter(): bool
    {
        if(isset($this->email)){
            if(!filter_var($this->email, FILTER_VALIDATE_EMAIL))
            {
                $this->error = 'email invalid';
                return false;
            }
            return true;
        }
        return true;
    }
    public function emailIsset(): bool
    {
        if(isset($this->email)){
            $users = new User();
            $user = $users->find('id', 'email=:email', ['email' => $this->email])->fetch();
            if($user)
            {
                if(!isset($this->id)){
                    $this->error = 'the email already exists';
                    return false;
                }
                if($this->id !== $user->id)
                {
                    $this->error = 'the email already exists in another account';
                    return false;
                }
                return true;
            }
            return true;
        }
        return true;
    }

    private function password(): bool
    {

        if(!empty($this->password)){
            $this->password =  password_hash($this->password, PASSWORD_BCRYPT, ['cost' => 12]);
            return true;
        }
        return true;
    }
    public function save(): bool
    {
        if($this->emailFilter() && $this->emailIsset() && $this->password()){
            return parent::save(); // TODO: Change the autogenerated stub
        }
        return false;
    }
}