<?php

namespace Source\Core;

class Response extends \Erykai\Response\Response
{
    private static $instance = null;

    private function __construct()
    {
    }

    public static function getInstance(): Response
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    public function json(): string
    {
        if (isset($this->getResponse()->data)) {
            $Cription = Cryption::getInstance();
            if (is_array($this->getResponse()->data)) {
                foreach ($this->getResponse()->data as $key => $value) {
                    $Cription = Cryption::getInstance();
                    if(isset($this->getResponse()->data[$key]->id)) {
                        $this->getResponse()->data[$key]->id = $Cription->encrypt($this->getResponse()->data[$key]->id);
                    }
                }
            } else {
                if(isset($this->getResponse()->data->id)) {
                    $this->getResponse()->data->id = $Cription->encrypt($this->getResponse()->data->id);
                }
            }
        }

        return parent::json(); // TODO: Change the autogenerated stub
    }
}