<?php

namespace Source\Core;


class Response extends \Erykai\Response\Response
{
    public function json(): string
    {
        if (isset($this->getResponse()->data)) {
            $Cription = new Cryption();
            if (is_array($this->getResponse()->data)) {
                foreach ($this->getResponse()->data as $key => $value) {
                    $Cription = new Cryption();
                    $this->getResponse()->data[$key]->id = $Cription->encrypt($this->getResponse()->data[$key]->id);
                }
            } else {
                $this->getResponse()->data->id = $Cription->encrypt($this->getResponse()->data->id);
            }
        }

        return parent::json(); // TODO: Change the autogenerated stub
    }
}